---
- name: Deploying WAR File to Tomcat
  hosts: all
  become: yes

  tasks:
    - name: Stop tomcat service
      service:
        name: tomcat
        state: stopped

    - name: Copy file into webapp folder
      copy:
        src: /home/admin/Desktop/practice/workspace/Maven/build/WebApp.war
        dest: /opt/tomcat/webapps/WebApp.war

    - name: Start tomcat service
      service:
        name: tomcat
        state: started
